# Generated by Django 4.2.2 on 2023-09-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марка',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель')),
                ('mar', models.ManyToManyField(to='cars.group', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuzov', models.CharField(max_length=50, verbose_name='Тип кузова:')),
                ('cvet', models.CharField(max_length=50, verbose_name='Цвет:')),
                ('vin', models.CharField(max_length=50, verbose_name='VIN:')),
                ('nom', models.CharField(max_length=50, verbose_name='Номер авто:')),
                ('compl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Комплектация:')),
                ('date', models.CharField(max_length=50, verbose_name='Год выпуска:')),
                ('nalli', models.BooleanField(default=False, verbose_name='В продаже')),
                ('price', models.IntegerField(verbose_name='Желаемая цена:')),
                ('probeg', models.IntegerField(verbose_name='Пробег:')),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото:')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото:')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото:')),
                ('email_mg', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail Менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL ОБЯЗАТЕЛЬНО! отображение на сайте')),
                ('trans', models.CharField(max_length=25, verbose_name='Трансмисия:')),
                ('obem', models.CharField(max_length=12, verbose_name='Объём:')),
                ('top', models.CharField(max_length=22, verbose_name='Топливо:')),
                ('priv', models.CharField(max_length=22, verbose_name='Привод:')),
                ('ls', models.CharField(max_length=22, verbose_name='Л.С')),
                ('pts', models.CharField(max_length=25, verbose_name='ПТС:')),
                ('vlad', models.IntegerField(verbose_name='Кол-во владельцев:')),
                ('tip_pts', models.CharField(blank=True, max_length=22, null=True, verbose_name='Тип ПТС:')),
                ('opis', models.CharField(max_length=22211, verbose_name='Описание:')),
                ('uchet', models.CharField(max_length=12, null=True, verbose_name='Стоит на учёте:')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона для связи:')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.group', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
