# Generated by Django 4.2.2 on 2023-09-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_model_country_model_marka_alter_marka_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Марки', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модели', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AddField(
            model_name='cars',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.marka', verbose_name='Марка:'),
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель:'),
        ),
    ]
