# Generated by Django 4.2.2 on 2023-09-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cuzov_alter_cars_cuzov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=40, verbose_name='Год выпуска:')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Год выпуска',
            },
        ),
        migrations.CreateModel(
            name='Obem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obem', models.CharField(max_length=40, verbose_name='Объём двигателя:')),
            ],
            options={
                'verbose_name': 'Объём двигателя',
                'verbose_name_plural': 'Объём двигателя',
            },
        ),
        migrations.CreateModel(
            name='Priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv', models.CharField(max_length=40, verbose_name='Привод:')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Привод',
            },
        ),
        migrations.CreateModel(
            name='Pts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts', models.CharField(max_length=40, verbose_name='ПТС:')),
            ],
            options={
                'verbose_name': 'ПТС',
                'verbose_name_plural': 'ПТС',
            },
        ),
        migrations.CreateModel(
            name='Sost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sost', models.CharField(max_length=40, verbose_name='Состояние:')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояние',
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=40, verbose_name='Тип двигателя:')),
            ],
            options={
                'verbose_name': 'Тип двигателя',
                'verbose_name_plural': 'Тип двигателя',
            },
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.CharField(max_length=40, verbose_name='Трансмисия:')),
            ],
            options={
                'verbose_name': 'Трансмисия',
                'verbose_name_plural': 'Трансмисия',
            },
        ),
        migrations.CreateModel(
            name='Uchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uchet', models.CharField(max_length=40, verbose_name='Учёт:')),
            ],
            options={
                'verbose_name': 'Учёт',
                'verbose_name_plural': 'Учёт',
            },
        ),
        migrations.RemoveField(
            model_name='cars',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='tip_pts',
        ),
        migrations.AddField(
            model_name='cars',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.data', verbose_name='Год выпуска:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='sost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.sost', verbose_name='Состояние:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='obem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.obem', verbose_name='Объём двигателя:'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='priv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.priv', verbose_name='Привод:'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='pts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.pts', verbose_name='ПТС:'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.top', verbose_name='Тип двигателя:'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.trans', verbose_name='Трансмисия:'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='uchet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.uchet', verbose_name='Стоит на учёте:'),
            preserve_default=False,
        ),
    ]
